### ISSUE TITLE
The quip API keeping throw below warning error from yesterday

### ISSUE THREAD

**Issue by wing324** [kenichi-ando/quip-api-java#10]
Hi,

I am try to read a quip table from the Quip API. It is able to read table. However, it keeps throwing an warning from yesterday.

`[WARN] Invalid cookie header: "Set-Cookie: AWSALBTG=xxx; Expires=Thu, 17 Feb 2022 05:20:08 GMT; Path=/". Invalid 'expires' attribute: Thu, 17 Feb 2022 05:20:08 GMT`

I was wondering could you please take a look? I fould a possble solution here: https://stackoverflow.com/questions/36473478/fixing-httpclient-warning-invalid-expires-attribute-using-fluent-api

**Comment by kenichi-ando** [comment]
Thank you for reporting the issue. I fixed it.
