### ISSUE TITLE
QuipThread.getTableById() only works for Spreadsheet, not Table

### ISSUE THREAD

**Issue by wing324** [kenichi-ando/quip-api-java#4]
Hi,

Thanks for this awesome API.

I found out that the API `QuipTable table = thread.getTableById(thread.getTableIds[0]);` is only able to get spreadsheet. 
There are two types of table in Quip Doc. One is Table, another one is Spreadsheet. It seems `getTableById` only works for spreadsheet.

How to produce:
Go to quip doc and insert a table(not spreadsheet). And then use above API to get the table. You will receive an error:
```
java.lang.NullPointerException: Cannot invoke "org.jsoup.nodes.Element.getElementsByTag(String)" because the return value of "org.jsoup.select.Elements.first()" is null
	at kenichia.quipapi.QuipTable._construct(QuipTable.java:177) ~[Java-Quip-api-1.x.jar:?]
	at kenichia.quipapi.QuipTable.<init>(QuipTable.java:35) ~[Java-Quip-api-1.x.jar:?]
	at kenichia.quipapi.QuipThread.getTableById(QuipThread.java:559) ~[Java-Quip-api-1.x.jar:?]
```

Thanks,
Min

**Comment by kenichi-ando** [comment]
Hi @wing324 , thanks for reporting the issue. I've fixed this issue. Thanks for your contribution!
